version: "3.7"
services:
    app:
        build:
            context: "./go"
            dockerfile: "go.dockerfile"
        container_name: "app_go"
        ports:
            - "8080:80"
        networks:
            - my_network
        depends_on:
            - "db"
        command: sh -c "/wait && go run main.go"
        environment:
            - WAIT_HOSTS=app_mariadb:3306
            - WAIT_HOSTS_TIMEOUT=300
            - WAIT_SLEEP_INTERVAL=30
            - WAIT_HOST_CONNECT_TIMEOUT=30
        #volumes:
        #- "./html/public/:/var/www/html/"
        #- "./html/errorpages/:/var/www/errorpages/"
        #- "./nginx/nginx.conf:/etc/nginx/conf.d/default.conf"
    db:
        build:
            context: "./mysql"
            dockerfile: "mariadb.dockerfile"
        container_name: app_mariadb
        restart: always
        networks:
            - my_network
        ports:
            - "3306:3306"
volumes:
    dbdata:
networks:
    my_network:
        driver: bridge
