version: "3.7"
services:
    app:
        build:
            context: "./go"
            dockerfile: "go.dockerfile"
        container_name: "app_go"
        ports:
            - "8080:80"
        #volumes:
        #- "./html/public/:/var/www/html/"
        #- "./html/errorpages/:/var/www/errorpages/"
        #- "./nginx/nginx.conf:/etc/nginx/conf.d/default.conf"
    db:
        build:
            context: "./mysql"
            dockerfile: "mariadb.dockerfile"
        container_name: app_mariadb
