name: API tests

on:
    push:
        branches:
            - main
            - test-integracion-continua
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Run docker and tests
              run: |
                  docker-compose up -d
                  docker exec -it app_go sh
                  cd api/tests && go test -v
                  exit
                  chmod +x ./stopdockers.sh
                  ./stopdockers.sh
