name: API tests

on:
    push:
        branches:
            - main
            - test-integracion-workflow
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Run docker and tests
              run: |
                  docker-compose up -d &&
              run: |
                  docker exec -t app_go sh
              run: |
                  cd api/tests && go test -v && exit
              run: |
                  chmod +x ./stopdockers.sh &&
                  ./stopdockers.sh
                  