name: API tests

on:
    push:
        branches:
            - main
            - test-integracion-workflow
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Run docker compose
              run: |
                  docker-compose up -d &&

            - name: Exec docker GO
              run: |
                  docker exec -t app_go sh

            - name: Run tests
              run: |
                  cd api/tests && go test -v && exit

            - name: Stops docker
              run: |
                  chmod +x ./stopdockers.sh &&
                  ./stopdockers.sh
