name: API tests

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Run docker compose
              run: |
                  docker-compose up -d

            - name: Create network
              run: |
                  docker network create testAPI

            - name: Build tests Dockerfile
              run: |
                  docker build -t tests .

            - name: Run fake DB
              run: |
                  docker run -d --net testAPI --name app_mariadb_fake fs5-gestiondesocios-backend_db

            - name: Run API tests
              run: |
                  docker run --net testAPI --name test_db tests

            - name: Stops docker containers
              run: |
                  chmod +x ./stopdockers.sh && ./stopdockers.sh
