name: Deploy to Digital Ocean droplet
on:
    push:
        branches:
            - main
            - integracion-continua
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Deploy to droplet using SSH
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USERNAME }}
                  password: ${{ secrets.PRIVATE_KEY }}
                  debug: true
                  script: |
                      cd fs5-gestiondesocios-backend/
                      git pull https://github.com/fullstacktf/fs5-gestiondesocios-backend.git
                      docker-compose up
