name: CICD

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Setup Go
              uses: actions/setup-go@v2
              with:
                  go-version: "1.15.3"

            - name: Install dependencies
              run: |
                  go version
                  go get -u golang.org/x/lint/golint

            - name: Run build
              run: cd go/src/ && go build .

            - name: Run vet & lint
              run: |
                  cd go/src/ && go vet .
                  golint .

            - name: Publish to Github Packages Registry
              uses: elgohr/Publish-Docker-Github-Action@master
              with:
                  name: dd8888/fs5-gestiondesocios-backend/CICD
                  registry: docker.pkg.github.com
                  username: ${{ secrets.GITHUB_USERNAME }}
                  password: ${{ secrets.GITHUB_TOKEN }}
                  dockerfile: Dockerfile-prod
                  tags: latest
